### ISSUE TITLE
Investigate mr-drupal

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/jenkins_github_drupal#8]
@wimleers has an [article](http://wimleers.com/article/mr-drupal) about using [mr](http://joeyh.name/code/mr/) to help automate Drupal maintenance. Let's discuss if this is something that might be helpful to incorporate into this project.

After a quick read, it would seem to me that mr is useful for maintenance and deployment, but this project is not so much about deployment as getting new test environments quickly spun up to test branches. So I'm not really sure how this would fit in here if at all.

**Comment by q0rban** [comment]
Yeah, I didn't read all of it, but sounds like this is more about managing lots of repositories, which I don't think is applicable here. Reopen if you disagree.

**Comment by wimleers** [comment]
It's definitely not an alternative to the whole set of things that this project does. But it _could_ be part of the whole system AFAICT.

You recommend to use https://github.com/Lullabot/drupal-boilerplate as part of using the system provided by this repository. There, it is recommend to put Drupal core in the `docroot` directory.

_That_ is where `mr-drupal` could be useful. Rather than checking in all of Drupal core (and not retaining all version history) and Drupal contrib modules, quite possibly through something like `wget foomodule.tar.gz; tar -xzf foomodule.tar.gz; git add foomodule; git ci -m "Added foomodule."`, you'd just declaratively state which modules should be checked out from `git.drupal.org`.

That's why I [reached out to @sirkitree](https://twitter.com/wimleers/status/376650247713615872): to check if you might be interested in combining it with `mr-drupal`, as part of this larger system.

**Comment by sirkitree** [comment]
I don't see any value in keeping git history for drupal itself. Perhaps the modules, but not core. At least I've never found a compelling reason to have it.

We also typically end up with repositories per project already, so it doesn't seem like it would be very helpful unless we were already using it on a project.

Might this be something to introduce into drupal-boilerplate instead?

**Comment by wimleers** [comment]
Even if not preserving Drupal/contrib module history, the process of updating a set of files to update core or a module is very bad: it's easy to forget to add a new file, or to delete a removed file. Something like `mr-drupal` makes it easy, because you just declare which version you want. And for that reason, it also _enforces_ supplying upstream patches, because you can't just one-off patch the version you checked in.

Yes, this might be something for `drupal-boilerplate`.
